# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/maple_dsds/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/sony/maple_dsds/proprietary
endif
